# Generated by Django 3.2.6 on 2021-12-16 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='wallet_recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wallet_recipient', to='finance.wallet', verbose_name='На кошелек'),
        ),
    ]
