# Generated by Django 3.2.6 on 2022-01-12 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_operation_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='category',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='wallet_recipient',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wallet_recipient', to='finance.wallet', verbose_name='На кошелек'),
        ),
    ]
